baseURL = "https://lemonsoda9013.github.io/"
languageCode = "en-us"
title = "LEMONSODA9013"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "LEMONSODA9013's Personal Homepage"
  images = ['/lemon.png']
  enableSearch = true


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Categories'
  params.header = true
  weight = 4
[[menu.main]]
  name = 'Original'
  url = '/articles/original'
  weight = 5
[[menu.main]]
  name = 'Collections'
  url = '/articles/collections'
  weight = 6
[[menu.main]]
  name = 'Minecraft@music'
  url = '/articles/minecraft'
  weight = 7
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 8
[[menu.main]]
  name = 'Github'
  url = 'https://github.com/lemonsoda9013'
  weight = 9

[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/lemonsoda9013'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/lemonsoda9013'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:z2285724939@gmail.com'
  weight = 3


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
